//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKutuphaneEntities : DbContext
    {
        public DBKutuphaneEntities()
            : base("name=DBKutuphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_OduncKitap> TBL_OduncKitap { get; set; }
        public virtual DbSet<TBL_Personel> TBL_Personel { get; set; }
        public virtual DbSet<TBL_Uyeler> TBL_Uyeler { get; set; }
        public virtual DbSet<TBL_Yazar> TBL_Yazar { get; set; }
        public virtual DbSet<TBL_Kasa> TBL_Kasa { get; set; }
        public virtual DbSet<TBL_Kitaplar> TBL_Kitaplar { get; set; }
    }
}
