//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Kitaplar()
        {
            this.TBL_OduncKitap = new HashSet<TBL_OduncKitap>();
        }
    
        public int ID { get; set; }
        public string Kitap_Adi { get; set; }
        public Nullable<int> Yazar_ID { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<int> Sayfa_Sayisi { get; set; }
        public string Yayin_Evi { get; set; }
        public string Basim_Yili { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TBL_Kategori TBL_Kategori { get; set; }
        public virtual TBL_Yazar TBL_Yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OduncKitap> TBL_OduncKitap { get; set; }
    }
}
